Login succesful.
[DEBUG] accesgranted was gelijk aan: True.
(['Die goldene Gans', '102 Dalmatians', 'Licence to Kill', 'The Greatest', 'U.S. Marshals', 'The Fighter', 'Des morceaux de moi', 'Mars Attacks!', "L'homme de l'ile Sandwich", 'Resident Evil: Extinction'], ['NPO3', 'NET5', 'RTL7', 'RTL8', 'Veronica', 'SBS9', 'TV5', 'NET5', 'TV5', 'RTL7'], ['http://www.filmtotaal.nl/film.php?id=26777', 'http://www.filmtotaal.nl/film.php?id=6751', 'http://www.filmtotaal.nl/film.php?id=522', 'http://www.filmtotaal.nl/film.php?id=20903', 'http://www.filmtotaal.nl/film.php?id=5005', 'http://www.filmtotaal.nl/film.php?id=18005', 'http://www.filmtotaal.nl/film.php?id=24488', 'http://www.filmtotaal.nl/film.php?id=2491', 'http://www.filmtotaal.nl/film.php?id=28256', 'http://www.filmtotaal.nl/film.php?id=13400'])
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:/Users/Steven/Desktop/MiniprojectProgramming/Programming/Tkinter.py", line 299, in <lambda>
    highlightcolor=highlightbuttoncolorthingy, command=(lambda: login()))
  File "C:/Users/Steven/Desktop/MiniprojectProgramming/Programming/Tkinter.py", line 103, in login
    goback(2)  # TODO: wanneer geactiveerd slaat hij de accesgranted screen over
  File "C:/Users/Steven/Desktop/MiniprojectProgramming/Programming/Tkinter.py", line 262, in goback
    filmscreen()
  File "C:/Users/Steven/Desktop/MiniprojectProgramming/Programming/Tkinter.py", line 43, in filmscreen
    lb = tk.Button(filmwindow, text=i + " (bekijk inhoud)", bg=background, activeforeground=activeforegroundbutton,
TypeError: can only concatenate list (not "str") to list
